version: '3'

services:
  poste-auction-notify:
    container_name: poste-auction-notify
    build: ./
    #command: python app.py
    command: tail -f /dev/null
    # environment is being taken from .env
    volumes:
      - ".:/app"